- pom.xml
- src/main/java/org/jahia/modules/tools/LoggerWrapper.java
- src/main/resources/groovyConsole.jsp
- src/main/resources/jcrConsole.jsp
- src/main/resources/log4jAdmin.jsp
- Fix issues with log4jadmin, Groovy console & JCR console
It seems we forgot to merge these changes.
> BACKLOG-6156-REPLACE-FELIX-WITH-KARAF

- pom.xml
https://jira.jahia.org/browse/BACKLOG-11875
> BACKLOG-11875 : Add module signature

- src/main/resources/functions.jspf
- src/main/resources/jcrIntegrityTools.jsp
https://jira.jahia.org/browse/IDEAS-1013
Added option in JCR Integrity Tools page to start integrity check from a given node.
> Added option to run integrity check on a subtree

- src/main/resources/jcrIntegrityTools.jsp
https://jira.jahia.org/browse/QA-12923
Query the database to find if UUID belong to an unmounted external provider
> QA-12923: Query the database to find if UUID belong to an unmounted external provider

- pom.xml
> BACKLOG-14377 - Updated scm version to match branch

- pom.xml
- src/main/java/org/jahia/modules/tools/taglibs/GroovyConsoleHelper.java
- src/main/resources/jcrConsole.jsp
- src/main/resources/log4jAdmin.jsp
https://jira.jahia.org/browse/QA-13589
Update to log4j2
> QA-13589: Update to log4j2

- pom.xml
- src/main/java/org/jahia/modules/tools/taglibs/GroovyConsoleHelper.java
- src/main/resources/jcrConsole.jsp
- src/main/resources/log4jAdmin.jsp
https://jira.jahia.org/browse/QA-13589
This reverts commit 8ba99013089706dafefbcb36c7c003f9c244a441.
> QA-13589: Revert - Update to log4j2

- src/main/resources/index.jsp
- src/main/resources/modules.jsp
https://jira.jahia.org/browse/BACKLOG-16205
New page listing modules, and allowing to reset startlevel to 90 if it's below 80
> BACKLOG-16205: Add tool to debug module start level

- src/main/resources/jcrQuery.jsp
https://jira.jahia.org/browse/SUP-107
> SUP-107 : count correctly nodes when doing a jcr query

- src/main/resources/jcrQuery.jsp
https://jira.jahia.org/browse/QA-14135
> SUP-107 : change label in query tools to avoid confusion

- src/main/resources/jcrBrowser.jsp
https://jira.jahia.org/browse/QA-14629
> QA-14629 : fix repository explorer link to use old theme

- src/main/resources/jcrIntegrityTools.jsp
https://jira.jahia.org/browse/QA-14731
> QA-14731: Log constraints errors

- src/main/resources/index.jsp
- src/main/resources/jcrJarsCleanup.jsp
https://jira.jahia.org/browse/QA-12887
> QA-12887: Add tools to remove unused jars

- src/main/resources/jcrBrowser.jsp
https://jira.jahia.org/browse/QA-14749 
Reset target and action when going to workspace. Added a video on the ticket.
> QA-14749 Reset target and action when going to workspace

- pom.xml
https://jira.jahia.org/browse/TECH-1297
> TECH-1297: Update jackrabbit dependency

- src/main/java/org/jahia/modules/tools/taglibs/GroovyConsoleHelper.java
- src/main/resources/jcrConsole.jsp
https://jira.jahia.org/browse/TECH-1027
> TECH-1027: Remove portlet references

- pom.xml
- src/main/resources/log4jAdmin.jsp
https://jira.jahia.org/browse/BACKLOG-21622
> BACKLOG-21622: USe 6.9 jahia plugin, import org.apache.logging.log4j,fix classloader hierarchy (highly flaky)

- package.json
- pom.xml
> TECH-1578: Updated module version to make room for a maintenance branch

- src/main/resources/jcrJarsCleanup.jsp
https://jira.jahia.org/browse/QA-15083
8.1.x port for https://github.com/Jahia/tools/pull/60
Add `toolAccessToken` in form
> QA-15083: Fix JCR jar cleanup tool in production

- pom.xml
https://jira.jahia.org/browse/TECH-1416
Update GraphQL DXM module dependency
> TECH-1416: Upgrade Guava or stop exposing it from core

- .github/workflows/on-code-change.yml
- pom.xml
- src/javascript/definitions.js
- src/main/resources/definitionsBrowser.jsp
- webpack.config.js
https://jira.jahia.org/browse/BACKLOG-22670
> BACKLOG-22670: fix delete definition button

- src/main/java/org/jahia/modules/tools/csrf/ToolsAccessTokenFilter.java
https://jira.jahia.org/browse/BACKLOG-22701
> BACKLOG-22701: fix concurrency issue in tools

- .github/maven.settings.xml
https://jira.jahia.org/browse/BACKLOG-22875
Used the settings from master branch
> BACKLOG-22875: Fix maven settings

- pom.xml
- src/main/java/org/jahia/modules/tools/search/ReIndexProxy.java
- src/main/resources/search.jsp
https://jira.jahia.org/browse/QA-15157
When triggering a re indexation of one or more workspace, setup the forceConsistencyCheck flag according to the given parameter. 
Make all the reindex option on a single command
> QA-15157: Factorize reindex options (workspace) and allow disabling consistency check

- .github/workflows/nightly-jahiaRL.yml
- .github/workflows/nightly-jahiaSN.yml
- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
https://jira.jahia.org/browse/PIPELINE-63
> PIPELINE-63: Execute Cypress tests via CI/CD

- tests/cypress/e2e/api/findDependencies.spec.ts
https://jira.jahia.org/browse/TECH-1954
Use cypress lib method for waiting probe to become GREEN before tests instead of local implem
> TECH-1954: Use JahiaCypress for waiting SAM to become green before test

- tests/package.json
- tests/yarn.lock
https://jira.jahia.org/browse/QABACKLOG-1610
> QABACKLOG-1610: Use the latest version of jahia-cypress in the tests

- src/main/java/org/jahia/modules/tools/gql/admin/osgi/Dependency.java
- tests/cypress/e2e/api/findDependencies.spec.ts
- tests/cypress/fixtures/findDependencies.graphql
https://jira.jahia.org/browse/BACKLOG-23176
Missing description in new tools field
> BACKLOG-23176: Avoid using enum in graphql to ensure good description

- .github/workflows/on-release.yml
- pom.xml
https://jira.jahia.org/browse/BACKLOG-23272
> BACKLOG-23272: Updated jahia-parent to 8.1.6.0

- src/main/resources/jcrQuery.jsp
https://jira.jahia.org/browse/QA-15179
> QA-15179 : restore js function in jcr query tools 

- src/main/java/org/jahia/modules/tools/ConfigurationCopier.java
- src/main/resources/support.jsp
Remove tools manager stuff from the code
> TECH-1707 Remove tools manager stuff from the code

- src/main/resources/renderFilters.jsp
Fixed the disable/enable labels into disabled/enabled as requested by Chikku.
> QA-15396: fix disable/enable labels

- src/javascript/provisioning.js
Updated the message following discussion with the team.
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)
> docs: updated message after provisioning script submitted

- pom.xml
- src/main/resources/functions.jspf
- src/main/resources/jcrIntegrityTools.jsp
- src/main/resources/textExtractor.jsp
Following maven import optimisation, some JSPs were missing some import.
They are now added
> fix: fix text etractor and jcr integrity tools

- src/main/java/org/jahia/modules/tools/JspPrecompileServlet.java
Add header and footer to jsp compilation page
> fix: fix add header/footer to jsp compilation page

- src/main/java/org/jahia/modules/tools/JspPrecompileServlet.java
- src/main/resources/commons/header.jspf
- src/main/resources/index.jsp
Add a label for the **jahia.environment** vairable. 
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)
> fix: add jahia env label

- .github/workflows/manual-run.yml
- .github/workflows/nightly-jahiaRL.yml
- .github/workflows/nightly-jahiaSN.yml
- .github/workflows/on-code-change.yml
- .github/workflows/on-merge.yml
- tests/.env.example
Migrate to Github packages
> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)
> chore: migrate to gh packages
